<a href="https://colab.research.google.com/github/Joeaviator/ABOUT-JOSHUA/blob/main/Aggregate_Functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import pandas as pd
import sqlite3

In [36]:
database='database.sqlite'
conn=sqlite3.connect(database)
print("Database connected sucessfully")

Database connected sucessfully

In [37]:
tables=pd.read_sql("""SELECT * FROM sqlite_master WHERE type='table';""",conn)
tables

,type,name,tbl_name,rootpage,sql
0,table,Player,Player,2,CREATE TABLE [Player] (\n\t[Player_Id]\tintege...
1,table,Extra_Runs,Extra_Runs,3,CREATE TABLE [Extra_Runs] (\n\t[Match_Id]\tint...
2,table,Batsman_Scored,Batsman_Scored,7,CREATE TABLE [Batsman_Scored] (\n\t[Match_Id]\...
3,table,Batting_Style,Batting_Style,10,CREATE TABLE [Batting_Style] (\n\t[Batting_Id]...
4,table,Bowling_Style,Bowling_Style,11,CREATE TABLE [Bowling_Style] (\n\t[Bowling_Id]...
5,table,Country,Country,12,CREATE TABLE [Country] (\n\t[Country_Id]\tinte...
6,table,Season,Season,14,CREATE TABLE [Season] (\n\t[Season_Id]\tintege...
7,table,City,City,15,CREATE TABLE [City] (\n\t[City_Id]\tinteger NO...
8,table,Outcome,Outcome,16,CREATE TABLE [Outcome] (\n\t[Outcome_Id]\tinte...
9,table,Win_By,Win_By,17,CREATE TABLE [Win_By] (\n\t[Win_Id]\tinteger N...
10,table,Wicket_Taken,Wicket_Taken,18,CREATE TABLE [Wicket_Taken] (\n\t[Match_Id]\ti...
11,table,Venue,Venue,21,CREATE TABLE [Venue] (\n\t[Venue_Id]\tinteger ...
12,table,Extra_Type,Extra_Type,23,CREATE TABLE [Extra_Type] (\n\t[Extra_Id]\tint...
13,table,Out_Type,Out_Type,24,CREATE TABLE [Out_Type] (\n\t[Out_Id]\tinteger...
14,table,Toss_Decision,Toss_Decision,25,CREATE TABLE [Toss_Decision] (\n\t[Toss_Id]\ti...
15,table,Umpire,Umpire,26,CREATE TABLE [Umpire] (\n\t[Umpire_Id]\tintege...
16,table,Team,Team,27,CREATE TABLE [Team] (\n\t[Team_Id]\tinteger NO...
17,table,Ball_by_Ball,Ball_by_Ball,28,CREATE TABLE [Ball_by_Ball] (\n\t[Match_Id]\ti...
18,table,sysdiagrams,sysdiagrams,31,CREATE TABLE [sysdiagrams] (\n\t[name]\tnvarch...
19,table,sqlite_sequence,sqlite_sequence,32,"CREATE TABLE sqlite_sequence(name,seq)"
20,table,Match,Match,34,CREATE TABLE [Match] (\n\t[Match_Id]\tinteger ...
21,table,Rolee,Rolee,36,CREATE TABLE [Rolee] (\n\t[Role_Id]\tinteger N...
22,table,Player_Match,Player_Match,37,CREATE TABLE [Player_Match] (\n\t[Match_Id]\ti...

In [38]:
#match details
matches=pd.read_sql("""SELECT * FROM Match;""",conn)
matches

,Match_Id,Team_1,Team_2,Match_Date,Season_Id,Venue_Id,Toss_Winner,Toss_Decide,Win_Type,Win_Margin,Outcome_type,Match_Winner,Man_of_the_Match
0,335987,2,1,2008-04-18 00:00:00,1,1,2,1,1,140.0,1,1.0,2.0
1,335988,4,3,2008-04-19 00:00:00,1,2,3,2,1,33.0,1,3.0,19.0
2,335989,6,5,2008-04-19 00:00:00,1,3,5,2,2,9.0,1,6.0,90.0
3,335990,7,2,2008-04-20 00:00:00,1,4,7,2,2,5.0,1,2.0,11.0
4,335991,1,8,2008-04-20 00:00:00,1,5,8,2,2,5.0,1,1.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
572,981016,6,2,2016-05-22 00:00:00,9,27,2,1,2,6.0,1,2.0,8.0
573,981018,13,2,2016-05-24 00:00:00,9,1,2,1,2,4.0,1,2.0,110.0
574,981020,11,1,2016-05-25 00:00:00,9,3,1,1,1,22.0,1,11.0,163.0
575,981022,13,11,2016-05-27 00:00:00,9,3,11,1,2,4.0,1,11.0,187.0
576,981024,2,11,2016-05-29 00:00:00,9,1,11,2,1,8.0,1,11.0,385.0

In [39]:
matches.isnull().sum()

Match_Id            0
Team_1              0
Team_2              0
Match_Date          0
Season_Id           0
Venue_Id            0
Toss_Winner         0
Toss_Decide         0
Win_Type            0
Win_Margin          9
Outcome_type        0
Match_Winner        3
Man_of_the_Match    3
dtype: int64

In [40]:
#Drop
matches.dropna(inplace=True)

In [41]:
#number of matches per season
results=pd.read_sql("""SELECT Season_Id, COUNT(*) AS TOTAL_MATCHES FROM Match GROUP BY Season_Id ORDER BY Season_Id;""",conn)
results

   Season_Id  TOTAL_MATCHES
0          1             58
1          2             57
2          3             60
3          4             73
4          5             74
5          6             76
6          7             60
7          8             59
8          9             60

In [42]:
team_result=pd.read_sql("""SELECT Match_Winner, COUNT(*) AS Wins FROM Match GROUP BY Match_Winner ORDER BY WINS DESC;""",conn)
team_result

    Match_Winner  Wins
0            7.0    80
1            3.0    79
2            2.0    70
3            1.0    68
4            5.0    63
5            4.0    63
6            6.0    56
7           11.0    34
8            8.0    29
9           10.0    12
10          13.0     9
11           9.0     6
12          12.0     5
13           NaN     3

In [43]:
team=pd.read_sql("""SELECT * FROM Team;""",conn)
team

    Team_Id                    Team_Name
0         1        Kolkata Knight Riders
1         2  Royal Challengers Bangalore
2         3          Chennai Super Kings
3         4              Kings XI Punjab
4         5             Rajasthan Royals
5         6             Delhi Daredevils
6         7               Mumbai Indians
7         8              Deccan Chargers
8         9         Kochi Tuskers Kerala
9        10                Pune Warriors
10       11          Sunrisers Hyderabad
11       12      Rising Pune Supergiants
12       13                Gujarat Lions

In [44]:
#Average win margin per season
win_margin=pd.read_sql("""SELECT Season_Id, AVG(Win_Margin) AS Average_Win_Margin FROM Match GROUP BY Season_Id ORDER BY Average_Win_Margin DESC;""",conn)
win_margin

   Season_Id  Average_Win_Margin
0          6           19.837838
1          3           19.762712
2          4           18.930556
3          8           17.821429
4          2           16.857143
5          5           16.229730
6          1           15.965517
7          9           15.333333
8          7           14.728814

In [45]:
#Number of matches played at each venue
venue_result=pd.read_sql("""SELECT Venue_Id, COUNT(*) AS Matches_Played FROM Match GROUP BY Venue_Id ORDER BY Matches_Played DESC""", conn)
venue_result

    Venue_Id  Matches_Played
0          1              58
1          5              54
2          3              53
3          4              49
4          8              48
5          7              41
6          2              35
7          6              33
8         26              17
9          9              17
10        12              15
11        19              12
12        13              12
13        25              11
14        18              11
15        22               9
16        32               8
17        15               8
18        33               7
19        31               7
20        29               7
21        28               7
22        20               7
23        11               7
24        10               7
25        30               6
26        27               6
27        34               5
28        23               5
29        21               3
30        16               3
31        14               3
32        35               2
33        24               2
34        17               2

In [48]:
#Count matches per winner per season
match_wins=pd.read_sql("""SELECT Season_Id, Match_Winner, COUNT(*) AS Wins
FROM Match
GROUP BY Season_Id,Match_Winner
ORDER BY Wins DESC;""", conn)
match_wins

    Season_Id  Match_Winner  Wins
0           1           5.0    13
1           6           7.0    13
2           5           1.0    12
3           6           3.0    12
4           7           4.0    12
..        ...           ...   ...
73          8           4.0     3
74          1           8.0     2
75          7           6.0     2
76          8           NaN     2
77          4           NaN     1

[78 rows x 3 columns]

In [49]:
#Top 5 players with the man of the match awards
man_of_match=pd.read_sql("""SELECT Man_of_the_Match, COUNT(*) AS AWARDS FROM Match GROUP BY Man_of_the_Match ORDER BY AWARDS DESC LIMIT 5;""",conn)
man_of_match

   Man_of_the_Match  AWARDS
0               162      17
1                31      16
2               110      15
3               187      14
4                57      13

In [50]:
#read player data whose ID=162
player1=pd.read_sql("""SELECT * FROM Player WHERE Player_Id=162;""",conn)
player1

,Player_Id,Player_Name,DOB,Batting_hand,Bowling_skill,Country_Name
0,162,CH Gayle,1979-09-21 00:00:00,1,2,8

In [51]:
#read player data whose ID=57
player2=pd.read_sql("""SELECT * FROM Player WHERE Player_Id=57;""",conn)
player2

,Player_Id,Player_Name,DOB,Batting_hand,Bowling_skill,Country_Name
0,57,RG Sharma,1987-04-30 00:00:00,2,2,1